// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3FvTCcx97psfrhFUP8IV3PPEENxdKH2E',
    appId: '1:678765323549:web:252e0a6a5492811c4d6df4',
    messagingSenderId: '678765323549',
    projectId: 'chatt-c59cd',
    authDomain: 'chatt-c59cd.firebaseapp.com',
    storageBucket: 'chatt-c59cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKfpcEJzsoG9JAiqmgjJMIQhr59X0Qv6c',
    appId: '1:678765323549:android:eba84f0d8e9ad0f04d6df4',
    messagingSenderId: '678765323549',
    projectId: 'chatt-c59cd',
    storageBucket: 'chatt-c59cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg7jn-hhu18AQAnpTQxj-MqFnuckiplW8',
    appId: '1:678765323549:ios:85bb346aecc3295d4d6df4',
    messagingSenderId: '678765323549',
    projectId: 'chatt-c59cd',
    storageBucket: 'chatt-c59cd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg7jn-hhu18AQAnpTQxj-MqFnuckiplW8',
    appId: '1:678765323549:ios:85bb346aecc3295d4d6df4',
    messagingSenderId: '678765323549',
    projectId: 'chatt-c59cd',
    storageBucket: 'chatt-c59cd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3FvTCcx97psfrhFUP8IV3PPEENxdKH2E',
    appId: '1:678765323549:web:2bbf6f832f144c894d6df4',
    messagingSenderId: '678765323549',
    projectId: 'chatt-c59cd',
    authDomain: 'chatt-c59cd.firebaseapp.com',
    storageBucket: 'chatt-c59cd.firebasestorage.app',
  );
}
